import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export const siteUrl = 'https://www.vertaosocorro.com.br';
const phone = '(31) 99157-9660';
const phoneLink = '+5531991579660';
const whatsapp = `https://wa.me/${phoneLink}?text=${encodeURIComponent('Olá! Vim pelo site da Vertão Resgate e gostaria de solicitar atendimento.')}`;
const instagram = 'https://www.instagram.com/vertao_resgate/';
const areaServed = ['Ipatinga, MG', 'Coronel Fabriciano, MG', 'Timóteo, MG', 'Caratinga, MG', 'Governador Valadares, MG', 'João Monlevade, MG', 'Manhuaçu, MG', 'Teófilo Otoni, MG'];

const services = [
  { slug: 'reboque-pesado', name: 'Reboque Pesado', title: 'Reboque Pesado em Ipatinga e Região | Vertão Resgate', description: 'Reboque pesado para caminhões e veículos pesados em Ipatinga, Vale do Aço e regiões de Minas Gerais.', intro: 'A Vertão Resgate realiza reboque pesado para caminhões e veículos pesados, com base em Ipatinga/MG e atendimento conforme a necessidade de cada operação.', detail: 'O serviço é indicado quando o deslocamento exige estrutura adequada ao porte do veículo. A equipe avalia as informações do chamado para orientar o atendimento e a logística necessária.', related: ['destombamento', 'auxilio-quinta-roda', 'reboque-extra-pesado'] },
  { slug: 'reboque-extra-pesado', name: 'Reboque Extra Pesado', title: 'Reboque Extra Pesado em Ipatinga MG | Vertão Resgate', description: 'Soluções de reboque extra pesado e operações especiais a partir de Ipatinga, Minas Gerais.', intro: 'A Vertão Resgate atende operações de reboque extra pesado e situações que demandam planejamento operacional específico.', detail: 'Cada solicitação é analisada de acordo com o tipo de veículo, condição da operação e rota necessária. A base da empresa fica em Ipatinga/MG, com atuação em diferentes regiões.', related: ['reboque-pesado', 'destombamento', 'transporte-de-maquinas'] },
  { slug: 'destombamento', name: 'Destombamento', title: 'Destombamento de Veículos em Ipatinga MG | Vertão Resgate', description: 'Operações de destombamento para veículos leves e pesados em Ipatinga, Vale do Aço e região.', intro: 'A Vertão Resgate realiza operações de destombamento para veículos leves e pesados, considerando as particularidades de cada ocorrência.', detail: 'O atendimento é organizado conforme as condições informadas no local e o tipo de veículo envolvido. Para solicitar apoio, envie as informações da operação pelo WhatsApp ou ligue diretamente.', related: ['reboque-pesado', 'reboque-extra-pesado', 'auxilio-quinta-roda'] },
  { slug: 'transporte-de-maquinas', name: 'Transporte de Máquinas', title: 'Transporte de Máquinas em Ipatinga e Região | Vertão Resgate', description: 'Transporte de máquinas e equipamentos a partir de Ipatinga/MG para operações em Minas Gerais e outros estados.', intro: 'A Vertão Resgate oferece transporte de máquinas e equipamentos, com base em Ipatinga/MG e planejamento de acordo com a demanda.', detail: 'O serviço atende operações que exigem movimentação e transporte especializado. A avaliação prévia ajuda a definir a solução apropriada para a máquina, equipamento e trajeto.', related: ['servico-munck', 'transporte-interestadual', 'reboque-extra-pesado'] },
  { slug: 'servico-munck', name: 'Serviço de Munck', title: 'Serviço de Munck em Ipatinga MG | Vertão Resgate', description: 'Movimentação e içamento de máquinas e equipamentos com serviço de Munck em Ipatinga e região.', intro: 'A Vertão Resgate disponibiliza serviço de Munck para movimentação e içamento de máquinas e equipamentos.', detail: 'O atendimento é tratado conforme o contexto operacional e as informações fornecidas pelo cliente. A empresa atua a partir de Ipatinga/MG para apoiar demandas na região e em rotas compatíveis.', related: ['transporte-de-maquinas', 'auxilio-quinta-roda', 'reboque-pesado'] },
  { slug: 'auxilio-quinta-roda', name: 'Auxílio Quinta Roda', title: 'Auxílio Quinta Roda em Ipatinga MG | Vertão Resgate', description: 'Apoio especializado para conjuntos e veículos pesados em Ipatinga, Vale do Aço e regiões atendidas.', intro: 'A Vertão Resgate presta auxílio de quinta roda para conjuntos e veículos pesados, com atendimento orientado pela necessidade da operação.', detail: 'As informações do veículo e da situação ajudam a equipe a encaminhar o suporte adequado. Para confirmar disponibilidade, entre em contato pelos canais da Vertão Resgate.', related: ['reboque-pesado', 'destombamento', 'reboque-extra-pesado'] },
  { slug: 'transporte-interestadual', name: 'Transporte Interestadual', title: 'Transporte Interestadual de Máquinas e Veículos | Vertão Resgate', description: 'Transporte de veículos, máquinas e equipamentos a partir de Minas Gerais para São Paulo, Espírito Santo e Bahia.', intro: 'A Vertão Resgate realiza operações de transporte a partir de Minas Gerais para outros estados, quando compatíveis com o tipo de serviço e a necessidade logística.', detail: 'Entre as rotas possíveis estão operações de transporte entre Minas Gerais e São Paulo, para o Espírito Santo — incluindo Vitória — e para a Bahia. Essas localidades são destinos ou rotas atendidas, não bases físicas da empresa.', related: ['transporte-de-maquinas', 'reboque-extra-pesado', 'reboque-pesado'] }
];

const regions = [
  { slug: 'ipatinga-mg', city: 'Ipatinga', title: 'Reboque Pesado e Destombamento em Ipatinga MG | Vertão Resgate', description: 'Reboque pesado, destombamento, transporte de máquinas e operações especiais em Ipatinga/MG.', intro: 'A Vertão Resgate tem base em Ipatinga/MG e realiza serviços de reboque, resgate e transporte para veículos, máquinas e equipamentos.', detail: 'Em Ipatinga, a empresa atende demandas de reboque leve, pesado e extra pesado, destombamento, auxílio de quinta roda, transporte de máquinas e operações especiais.' },
  { slug: 'coronel-fabriciano-mg', city: 'Coronel Fabriciano', title: 'Reboque Pesado em Coronel Fabriciano MG | Vertão Resgate', description: 'Reboque pesado, destombamento e transporte especializado na região de Coronel Fabriciano/MG.', intro: 'Com base em Ipatinga/MG, a Vertão Resgate realiza operações de reboque e transporte na região de Coronel Fabriciano.', detail: 'O atendimento é alinhado ao tipo de ocorrência, incluindo apoio para veículos leves e pesados, destombamento e transporte de máquinas quando aplicável.' },
  { slug: 'timoteo-mg', city: 'Timóteo', title: 'Reboque e Destombamento em Timóteo MG | Vertão Resgate', description: 'Atendimento de reboque, destombamento e transporte de máquinas na região de Timóteo/MG.', intro: 'A Vertão Resgate, com base em Ipatinga/MG, atende operações de reboque, resgate e transporte na região de Timóteo.', detail: 'A proximidade com o Vale do Aço permite organizar atendimentos para demandas de veículos, conjuntos pesados, máquinas e equipamentos conforme a operação.' },
  { slug: 'caratinga-mg', city: 'Caratinga', title: 'Reboque Pesado em Caratinga MG | Vertão Resgate', description: 'Reboque pesado, transporte de máquinas e operações especiais na região de Caratinga/MG.', intro: 'A Vertão Resgate realiza operações de reboque e transporte na região de Caratinga a partir de sua base em Ipatinga/MG.', detail: 'O suporte pode incluir reboque pesado, destombamento, transporte de máquinas e outras operações compatíveis com a demanda e o trajeto.' },
  { slug: 'governador-valadares-mg', city: 'Governador Valadares', title: 'Reboque Pesado em Governador Valadares MG | Vertão Resgate', description: 'Serviços de reboque pesado, destombamento e transporte na região de Governador Valadares/MG.', intro: 'Com base em Ipatinga/MG, a Vertão Resgate atende operações de reboque e transporte na região de Governador Valadares.', detail: 'O planejamento considera a rota, o porte do veículo ou equipamento e as condições da solicitação para direcionar o serviço adequado.' },
  { slug: 'joao-monlevade-mg', city: 'João Monlevade', title: 'Reboque e Transporte em João Monlevade MG | Vertão Resgate', description: 'Reboque, transporte de máquinas e operações especiais para a região de João Monlevade/MG.', intro: 'A Vertão Resgate atende a região de João Monlevade com operações de reboque, resgate e transporte realizadas a partir de Ipatinga/MG.', detail: 'A empresa avalia cada chamado para apoiar o deslocamento de veículos, máquinas e equipamentos conforme as necessidades apresentadas.' },
  { slug: 'manhuacu-mg', city: 'Manhuaçu', title: 'Reboque Pesado em Manhuaçu MG | Vertão Resgate', description: 'Reboque pesado, destombamento e transporte de máquinas na região de Manhuaçu/MG.', intro: 'A Vertão Resgate realiza operações de reboque e transporte na região de Manhuaçu, tendo Ipatinga/MG como sua base principal.', detail: 'O atendimento pode envolver reboque pesado, transporte de máquinas, destombamento e operações especiais, sempre conforme o cenário informado.' },
  { slug: 'teofilo-otoni-mg', city: 'Teófilo Otoni', title: 'Reboque Pesado em Teófilo Otoni MG | Vertão Resgate', description: 'Atendimento de reboque pesado, transporte e operações especiais na região de Teófilo Otoni/MG.', intro: 'A Vertão Resgate atende operações de transporte e reboque na região de Teófilo Otoni a partir de sua base em Ipatinga/MG.', detail: 'Para rotas mais longas, a definição do atendimento considera as informações do veículo ou equipamento, origem, destino e condições operacionais.' },
  { slug: 'muriae-mg', city: 'Muriaé', title: 'Reboque e Transporte em Muriaé MG | Vertão Resgate', description: 'Reboque, transporte de máquinas e operações especiais para a região de Muriaé/MG.', intro: 'A Vertão Resgate, sediada em Ipatinga/MG, realiza operações de reboque e transporte na região de Muriaé quando compatíveis com a demanda.', detail: 'O contato prévio permite orientar o serviço para veículos, máquinas e equipamentos e avaliar a melhor organização da rota.' },
  { slug: 'belo-horizonte-mg', city: 'Belo Horizonte', title: 'Reboque Pesado e Transporte para Belo Horizonte MG | Vertão Resgate', description: 'Operações de reboque pesado e transporte a partir de Ipatinga para a região de Belo Horizonte/MG.', intro: 'A Vertão Resgate realiza operações de reboque e transporte para a região de Belo Horizonte, partindo de sua base em Ipatinga/MG.', detail: 'Belo Horizonte é atendida como região de operação e rota de transporte; a empresa não informa base física na capital.' }
];

const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const schema = data => `<script type="application/ld+json">${JSON.stringify(data)}</script>`;
const crumbs = (name, url, group) => ({ '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Início', item: siteUrl + '/' }, { '@type': 'ListItem', position: 2, name: group, item: siteUrl + (group === 'Serviços' ? '/#servicos' : '/atendimento/') }, { '@type': 'ListItem', position: 3, name, item: url }] });

function header() { return `<header class="header scrolled seo-header"><a class="brand" href="/" aria-label="Vertão Resgate - início"><img decoding="async" src="/assets/logo.png" width="320" height="320" alt="Vertão Resgate"></a><button class="menu-toggle" aria-label="Abrir menu" aria-expanded="false"><span></span><span></span><span></span></button><nav aria-label="Navegação principal"><a href="/#servicos">Serviços</a><a href="/atendimento/">Regiões atendidas</a><a href="/#sobre">Sobre</a><a href="/#contato">Contato</a></nav><a class="header-cta" href="${whatsapp}" target="_blank" rel="noreferrer">Solicitar atendimento</a></header>`; }
function footer() { return `<footer><div class="container footer-grid"><div><img decoding="async" src="/assets/logo.png" width="320" height="320" alt="Vertão Resgate"><p>Reboque, resgate, transporte de máquinas e operações especiais com base em Ipatinga/MG.</p></div><div><p class="footer-label">Serviços</p><a href="/reboque-pesado/">Reboque pesado</a><a href="/destombamento/">Destombamento</a><a href="/transporte-de-maquinas/">Transporte de máquinas</a></div><div><p class="footer-label">Contato</p><a href="tel:${phoneLink}">${phone}</a><a href="${whatsapp}" target="_blank" rel="noreferrer">Chamar no WhatsApp</a><a href="${instagram}" target="_blank" rel="noreferrer">Instagram @vertao_resgate ↗</a><p>Rua Apucarana, 235<br>Bairro Caravelas<br>Ipatinga - MG</p></div></div><div class="container copyright">© <span id="year"></span> Vertão Resgate. Todos os direitos reservados.</div></footer>`; }
function layout({ title, description, canonical, breadcrumb, body, structured }) { return `<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${canonical}"><link rel="icon" href="/assets/logo.png" type="image/png"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${siteUrl}/assets/estrutura-operacional.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/styles.css"></head><body>${header()}<main class="seo-page"><div class="container seo-container"><nav class="breadcrumbs" aria-label="Caminho de navegação"><a href="/">Início</a><span>›</span><a href="${breadcrumb.group === 'Serviços' ? '/#servicos' : '/atendimento/'}">${breadcrumb.group}</a><span>›</span><span aria-current="page">${breadcrumb.name}</span></nav>${body}</div></main>${footer()}<dialog class="lightbox"><button class="close" aria-label="Fechar galeria">×</button><button class="previous" aria-label="Imagem anterior">←</button><img src="" alt=""><button class="next" aria-label="Próxima imagem">→</button><p></p></dialog>${schema(breadcrumb.schema)}${schema(structured)}<script src="/app.js" defer></script></body></html>`; }

function servicePage(item) { const url = `${siteUrl}/${item.slug}/`; const breadcrumb = { name: item.name, group: 'Serviços', schema: crumbs(item.name, url, 'Serviços') }; const related = item.related.map(slug => services.find(x => x.slug === slug)).map(x => `<a href="/${x.slug}/">${x.name}</a>`).join(''); const structured = { '@context': 'https://schema.org', '@type': 'Service', name: item.name, serviceType: item.name, description: item.description, provider: { '@type': 'LocalBusiness', name: 'Vertão Resgate', telephone: phone, address: { '@type': 'PostalAddress', streetAddress: 'Rua Apucarana, 235, Bairro Caravelas', addressLocality: 'Ipatinga', addressRegion: 'MG', addressCountry: 'BR' } }, areaServed: areaServed.map(name => ({ '@type': 'City', name })) }; const body = `<p class="eyebrow">Serviços Vertão Resgate</p><h1>${item.name} em Ipatinga e Região</h1><p class="seo-lead">${item.intro}</p><section class="seo-grid"><div><h2>Como funciona o atendimento</h2><p>${item.detail}</p><h2>Área de atendimento</h2><p>A Vertão Resgate atende Ipatinga, Vale do Aço e outras regiões de Minas Gerais. Para operações de transporte, a viabilidade é confirmada conforme a rota e o serviço solicitado.</p></div><aside class="seo-contact"><p class="eyebrow">Atendimento direto</p><h2>Precisa de apoio?</h2><a class="button primary" href="${whatsapp}" target="_blank" rel="noreferrer">Solicitar atendimento</a><a class="phone" href="tel:${phoneLink}">${phone}</a></aside></section><section class="seo-links"><h2>Serviços relacionados</h2><div>${related}</div><p><a href="/atendimento/">Ver regiões atendidas</a></p></section>`; return { path: `${item.slug}/index.html`, html: layout({ ...item, canonical: url, breadcrumb, body, structured }) }; }

function regionPage(item) { const url = `${siteUrl}/atendimento/${item.slug}/`; const breadcrumb = { name: item.city, group: 'Regiões atendidas', schema: crumbs(item.city, url, 'Regiões atendidas') }; const links = ['reboque-pesado', 'destombamento', 'transporte-de-maquinas'].map(slug => services.find(x => x.slug === slug)).map(x => `<a href="/${x.slug}/">${x.name}</a>`).join(''); const neighbours = regions.filter(x => x.slug !== item.slug).slice(0, 3).map(x => `<a href="/atendimento/${x.slug}/">${x.city}</a>`).join(''); const structured = { '@context': 'https://schema.org', '@type': 'Service', name: `Reboque e transporte na região de ${item.city}`, serviceType: 'Reboque, resgate e transporte', provider: { '@type': 'LocalBusiness', name: 'Vertão Resgate', url: siteUrl, telephone: phone, address: { '@type': 'PostalAddress', streetAddress: 'Rua Apucarana, 235, Bairro Caravelas', addressLocality: 'Ipatinga', addressRegion: 'MG', addressCountry: 'BR' } }, areaServed: { '@type': 'City', name: `${item.city}, MG` } }; const body = `<p class="eyebrow">Região atendida</p><h1>Reboque Pesado e Destombamento em ${item.city} – MG</h1><p class="seo-lead">${item.intro}</p><section class="seo-grid"><div><h2>Operações na região de ${item.city}</h2><p>${item.detail}</p><h2>Serviços disponíveis</h2><p>A Vertão Resgate trabalha com reboque leve, pesado e extra pesado, destombamento, transporte de máquinas, serviço de Munck, auxílio de quinta roda e operações especiais, conforme o tipo de atendimento.</p></div><aside class="seo-contact"><p class="eyebrow">Base em Ipatinga/MG</p><h2>Solicite atendimento</h2><a class="button primary" href="${whatsapp}" target="_blank" rel="noreferrer">Chamar no WhatsApp</a><a class="phone" href="tel:${phoneLink}">${phone}</a></aside></section><section class="seo-links"><h2>Encontre o serviço certo</h2><div>${links}</div><h2>Cidades atendidas</h2><div>${neighbours}</div></section>`; return { path: `atendimento/${item.slug}/index.html`, html: layout({ ...item, canonical: url, breadcrumb, body, structured }) }; }

function regionsHub() { const canonical = `${siteUrl}/atendimento/`; const list = regions.map(x => `<a href="/atendimento/${x.slug}/">${x.city} – MG</a>`).join(''); const body = `<p class="eyebrow">Vertão Resgate</p><h1>Regiões atendidas</h1><p class="seo-lead">A Vertão Resgate tem base em Ipatinga/MG e realiza operações de reboque, resgate e transporte em cidades de Minas Gerais e em rotas para outros estados.</p><section class="seo-links"><h2>Principais regiões</h2><div>${list}</div></section><section class="seo-grid"><div><h2>Outras regiões de Minas Gerais</h2><p>A empresa também atende, conforme a operação, Abre Campo, Rio Casca, Realeza, Naque, Periquito, São Domingos do Prata e Cava Grande.</p><h2>Operações interestaduais</h2><p>Para transportes compatíveis, a Vertão Resgate atende rotas para São Paulo, Espírito Santo — incluindo Vitória — e Bahia. Essas localidades são destinos de operação, não bases físicas da empresa.</p></div><aside class="seo-contact"><h2>Fale com a equipe</h2><a class="button primary" href="${whatsapp}" target="_blank" rel="noreferrer">Solicitar atendimento</a><a class="phone" href="tel:${phoneLink}">${phone}</a></aside></section>`; const breadcrumb = { name: 'Regiões atendidas', group: 'Regiões atendidas', schema: { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Início', item: siteUrl + '/' }, { '@type': 'ListItem', position: 2, name: 'Regiões atendidas', item: canonical }] } }; return { path: 'atendimento/index.html', html: layout({ title: 'Regiões Atendidas | Vertão Resgate', description: 'Vertão Resgate: reboque, transporte e operações especiais em Ipatinga, Vale do Aço e regiões de Minas Gerais.', canonical, breadcrumb, body, structured: { '@context': 'https://schema.org', '@type': 'Service', name: 'Reboque e transporte em regiões atendidas', provider: { '@type': 'LocalBusiness', name: 'Vertão Resgate', telephone: phone }, areaServed } }) }; }

export async function writeSeoPages(outputDir) { const pages = [...services.map(servicePage), ...regions.map(regionPage), regionsHub()]; for (const page of pages) { const filename = join(outputDir, page.path); await mkdir(join(filename, '..'), { recursive: true }); await writeFile(filename, page.html); } const urls = ['/', ...services.map(x => `/${x.slug}/`), '/atendimento/', ...regions.map(x => `/atendimento/${x.slug}/`)]; const sitemap = `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map((path, index) => `<url><loc>${siteUrl}${path}</loc><changefreq>monthly</changefreq><priority>${index === 0 ? '1.0' : '0.8'}</priority></url>`).join('')}</urlset>`; await writeFile(join(outputDir, 'sitemap.xml'), sitemap); }
